// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKdslp1mW8oGljanEHhzXzx2lnDI_GM-o',
    appId: '1:124097093343:web:1a3e0e50d0ad16edc5d36a',
    messagingSenderId: '124097093343',
    projectId: 'resource-shelf',
    authDomain: 'resource-shelf.firebaseapp.com',
    storageBucket: 'resource-shelf.firebasestorage.app',
    measurementId: 'G-8WDRTDDGCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69YZVkjelxpGpOOubSGm1LmN8i-E_6wI',
    appId: '1:124097093343:android:e550a1db7a0fa0eec5d36a',
    messagingSenderId: '124097093343',
    projectId: 'resource-shelf',
    storageBucket: 'resource-shelf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZ8Tt-oUTVqiXcnGMvHWcT9r3OLWji70',
    appId: '1:124097093343:ios:a3f20edee5edaa28c5d36a',
    messagingSenderId: '124097093343',
    projectId: 'resource-shelf',
    storageBucket: 'resource-shelf.firebasestorage.app',
    iosBundleId: 'com.example.resourceShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZ8Tt-oUTVqiXcnGMvHWcT9r3OLWji70',
    appId: '1:124097093343:ios:a3f20edee5edaa28c5d36a',
    messagingSenderId: '124097093343',
    projectId: 'resource-shelf',
    storageBucket: 'resource-shelf.firebasestorage.app',
    iosBundleId: 'com.example.resourceShelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKdslp1mW8oGljanEHhzXzx2lnDI_GM-o',
    appId: '1:124097093343:web:924d567d14fc8e33c5d36a',
    messagingSenderId: '124097093343',
    projectId: 'resource-shelf',
    authDomain: 'resource-shelf.firebaseapp.com',
    storageBucket: 'resource-shelf.firebasestorage.app',
    measurementId: 'G-VH6ZLS173Z',
  );
}
